### ISSUE TITLE
멤버십 모달 공통화하는 방법에 대한 질문

### ISSUE THREAD

**Issue by stnqls** [code-in-design/pass-frontend#10]
# 상황설명

합격분석에서 멤버십 구매하기 버튼을 눌렀을때 `멤버십 안내 모달`을 나타내야하는데,

### 멤버십 안내 모달
![image](https://github.com/code-in-design/pass-frontend/assets/81519415/716841c0-9867-4586-9743-156776657a54)

현재는 메인홈의 "멤버십안내" 버튼을 눌렀을때 `멤버십안내모달`이 뜨고 있습니다.
(여기서 멤버십안내버튼은 ServiceListItem 이라는 컴포넌트로 만들었습니다.)

### 메인 홈에서 만든 모달(멤버십안내)
![image](https://github.com/code-in-design/pass-frontend/assets/81519415/1012bf1e-c057-42bf-8fed-faac24cb3c55)

지금 합격분석에서 구현을 하다보니, 멤버십 구매하기를 클릭했을때 동일한 `멤버십 안내모달` 이 보여야해서, `멤버십 안내모달`을 공통화 하려고 합니다.

### 합격분석 멤버십 안내 모달(멤버십 구매하기)
![image](https://github.com/code-in-design/pass-frontend/assets/81519415/784d4da7-c05f-430e-85b1-4ef8d1361e35)

지금 멤버십 안내 모달은 features/membership 안에 모달 파일이 있는데, 모달 안에서 홈화면의 멤버십 안내 버튼이 같이 있습니다.

<img width="2459" alt="image" src="https://github.com/code-in-design/pass-frontend/assets/81519415/79934632-b33e-4609-9fd9-f5012c834c32">

# 질문
src/components/modal에 따로 분리를 해야할것같은데 제가 생각해본 방법은 다음과 같습니다.
방법 1.
모달 내부 컨텐츠를 공통으로 빼고서 modal오픈하는 방식을 다른 방법을 사용
방법 2.
MembershipModal 컴포넌트안에 `멤버십안내버튼`과 `멤버십구매버튼`  두개를 만들어두고 MembershipModal의 Props로 어떤 버튼을 렌더링하게 하는 방법

# 레퍼런스 및 관련 링크
https://www.figma.com/file/Bcs7XFeQCkGcFKEv0c4dp3/z-one-wireframe?type=design&node-id=965-44036&t=SmdrVOLgQGDHOVVU-4

**Comment by simsimjae** [comment]
방법1이 적합해보입니다. 모달 내부 컨텐츠만 공통으로 빼고 modal은 각각의 features에 들어가는게 맞는것같습니다.

**Comment by simsimjae** [comment]
질문 내용 해결 됬으면 클로즈해주시면 됩니다~
