### ISSUE TITLE
[합격분석] 실기기록입력에서 라디오버튼의 상태가 유지되지 않는 문제에대해 질문합니다.

### ISSUE THREAD

**Issue by stnqls** [code-in-design/pass-frontend#14]
# 상황설명
실기 기록 입력을 Radio를 사용할때, 선택했던 값이 check가 되어있지 않은 문제가 있습니다.
재현 경로
1. 실기 기록입력 radio 선택
2. 다음버튼누름
3. 다른 실기 기록입력 radio선택
4. 이전버튼누름

값을 직접 입력할 경우에는 잘 작동을하는데 radio로 선택할 경우엔 선택했던 값이 check가 되어있지 않습니다.

![image](https://github.com/code-in-design/pass-frontend/assets/81519415/df6fcc79-bfcf-493e-b1fc-6df69efa357b)

getValues()를 통해 console.log()로 확인해보면 눌렀던 값이 출려이 되는데, radio에 체크가 되도록하는 방법을 모르겠습니다.

```tsx
{props?.practicalScore ? (
          // 객관식 입력
          <Content>
            <RadioGroup>
              <Stack direction="column">
                {props?.practicalScore.map((item, index) => {
                  console.log(item, props.getValues(exerciseIcon.text) === item);
                  return (
                    <Radio {...props.register(exerciseIcon.text, { required: '점수를 선택해주세요', onChange: e => props.setValue(exerciseIcon.text, e.target.value) })} key={index} value={item} variant="outline" >
                      {item}
                    </Radio>
                  );
                })}
              </Stack>
            </RadioGroup>
          </Content>
        ) : (
          // 주관식 입력
          <Content>
            <InputWrapper>
              <Input {...props.register(exerciseIcon.text, { value: '', required: '점수를 입력해주세요' })} />
              <MetricUnits>cm</MetricUnits>
            </InputWrapper>
          </Content>
        )}

```
exerciseIcon.text는 실기 과목명을, props.getValues(exerciseIcon.text)를할경우 라디오버튼의 label값을 나타냅니다. (3초 이상 유지 후 배근력 깔끔하게 수행)

# 질문
1.  radio에 checked 를통해 getValues()를통해 가져온 값과 radio의 value값이 같으면 checked가 true가 되도록 시도해봤는데 안됩니다. 어떻게 해야할까요?

# 레퍼런스 및 관련 링크
1. #9
2. https://github.com/code-in-design/pass-frontend/pull/9/commits/f8ad16e556a88cc3e9db0be9109e41f4a96c4bef

**Comment by simsimjae** [comment]
코드를 봐야 알것같긴한데, 아마 다음버튼을 눌렀을때 이전 화면에서의 라디오버튼이 완전히 제거되어서 그런거같아요 다음버튼을 눌러도 DOM Tree에 남아있어야할것같습니다!

**Comment by simsimjae** [comment]
https://chat.openai.com/share/15c78377-85e0-4dea-8657-9149c84a57e6
한번 참고해서 해결해보시겠어요

**Comment by simsimjae** [comment]
그리고 register할때 input의 name에는 텍스트가 아니라 각 객관식 항목에 대한 ID값을 임의로 설정해서 넣어야할것같아요

**Comment by stnqls** [comment]
RadioGroup에 `defaultValue={props.getValues(exerciseIcon.text)}` 를 추가해서 선택되게 만들었는데, 제일 처음 radio만 선택이 안됩니다...

**Comment by stnqls** [comment]
부모 컴포넌트에서 state가 변경되어 발생했던 문제로 state와 실기종목 전체를 사용하는 컴포넌트에 props(types,step)으로 넘겨 해결했습니다.

**Comment by simsimjae** [comment]
@stnqls 부모 컴포넌트에서 state가 변경되면서 하위 컴포넌트가 리렌더링되어서 이전에 넣었던값이 날라간거였나요?
