### ISSUE TITLE
[합격분석] 합격분석메뉴의 container통합여부에대해 질문드립니다.

### ISSUE THREAD

**Issue by stnqls** [code-in-design/pass-frontend#15]
# 배경설명
합격분석 페이지에서 대학교를 선택한뒤에 합격분석 창이 보이기 전에 점수 입력여부, 엠버십,분석열람권여부, 내신반영여부, 실기반영여부 등 확인하는 과정이 많은데, 현재는 pages폴더 안에 분기 없이 주석으로 보여지고 있습니다.

<img width="1432" alt="image" src="https://github.com/code-in-design/pass-frontend/assets/81519415/e4c9efe8-d9f9-4d05-9da5-0fd0fe4df7b7">

# 문제상황
1.
2.

# 재현방법
1.
2.

# 시도해본 방법
1.
2.

# 질문
1. menu === "passAnalysis"로 묶여있는 컨테이너들을 통합하는 하나의 컨테이너 안에서해도 되나요? 아니면 지금 같은페이지에서 한번에 해도 되나요?

# 관련 링크 (피그마, PR링크 등..)
1. https://www.figma.com/file/r6WwDA4TgjyHqrXEx6sHhq/Z-ONE-Flow-Chart?type=whiteboard&node-id=122-233&t=BXO3aYro5BMKApmG-0
2.

# 소요시간

# 주의사항
---
1. 배경설명은 리뷰어가 글만 보고 이해할 수 있도록 글과 사진을 활용하여 최대한 상세하게 설명해주세요.
2. 리뷰어가 해당 현상을 재현해볼 수 있도록 재현방법 또는 재현경로를 스텝별로 적어주세요.
3. 문제를 해결하기 위해 시도하거나 알아본 방법들을 적어주세요.
4. 리뷰어가 본문 내용에 모르는게 있다고 생각이 들때는 피그마 링크 또는 관련 캡쳐화면도 같이 넣어주세요.
5. 링크 부분에 PR링크도 같이 남겨주세요. (리뷰어가 코드를 바로 확인해볼 수 있도록)
6. 소요시간은 질문을 고민하고 해결하는데 걸린 대략적인 시간을 시간단위로 적어주세요.

**Comment by simsimjae** [comment]
비어있는 질문 항목은 제거하고 올려주세요~!

**Comment by simsimjae** [comment]
굳이 컨테이너로 한번 더 묶을필요는 없어보이고 지금도 괜찮은것같습니다~!
