### ISSUE TITLE
[메인홈] 폴더링 구조 질문드립니다.

### ISSUE THREAD

**Issue by stnqls** [code-in-design/pass-frontend#19]
# 배경설명
메인 홈 화면에서, 
- 나의 관심대학, 실시간 인기 대학학과는 `features/universities/` 에 위치해있고,
- 업데이트 일시 & comment 는 `features/versions` 에 위치해있는고
- 안녕하세요, 00 님! 대학찾기, 합격분석 버튼까지는 `features/selcomeSection`에 위치해있습니다.

![image](https://github.com/code-in-design/pass-frontend/assets/81519415/248f8c77-e4c5-4cbb-a6f3-eedfead9ec35)

그런데, 서비스 바로가기나 지원 가능성 & 합격 확률은 지금 `pages/index/` 에 위치해있습니다.

<img width="406" alt="image" src="https://github.com/code-in-design/pass-frontend/assets/81519415/c9b6b40e-ef9f-4027-a1d6-4bc2c1a1b40b">

# 질문
1. 파일 구조를 변경해야할까요?

# 주의사항
---
1. 배경설명은 리뷰어가 글만 보고 이해할 수 있도록 글과 사진을 활용하여 최대한 상세하게 설명해주세요.
2. 리뷰어가 해당 현상을 재현해볼 수 있도록 재현방법 또는 재현경로를 스텝별로 적어주세요.
3. 문제를 해결하기 위해 시도하거나 알아본 방법들을 적어주세요.
4. 리뷰어가 본문 내용에 모르는게 있다고 생각이 들때는 피그마 링크 또는 관련 캡쳐화면도 같이 넣어주세요.
5. 링크 부분에 PR링크도 같이 남겨주세요. (리뷰어가 코드를 바로 확인해볼 수 있도록)
6. 소요시간은 질문을 고민하고 해결하는데 걸린 대략적인 시간을 시간단위로 적어주세요.

**Comment by simsimjae** [comment]
WelcomeSection의 user name이 필요해서 feautres로 빼신것같은데 피쳐로 빼는것의 기준은 단순히 데이터 연동이 필요할때 뺸다기보다는 지금 빼려고하는게 하나의 도메인에 속하는지를 고민해보고 결정하면 좋을것같아요 예를들어서 WelcomeSection이라는거는 어떤 도메인이라기보다는(유저, 포트폴리오, 내점수, 대학 등등..과 확연하게 구분됨) 그냥 UI의 일부를 나타내는거잖아요? 그래서 별도로 features로 뺴는게 부적합해보입니다.

그냥 Container없이 페이지 컴포넌트에서 바로 데이터 호출을해서 name을 넘겨주는게 좋을것같습니다.

**Comment by simsimjae** [comment]
위에 설명은 좋았는데

파일 구조를 변경해야할까요?

질문이 어떤 파일을 어떻게 변경할것으로 생각하신건지 좀 더 자세히 설명해주시면 좋을것같아요

**Comment by stnqls** [comment]
welcomSection이 features에 있어서 pages에 index에 probability나 serviceList처럼 해야할지, 아니면 pages/index에 있는 probability나 serviceList가 welcomeSection처럼 features로 가야할지 고민이었는데, welcomeSection을 pages로 옮겨서 바로 사용한다면, welcomSection만 pages/index로 옮기면 되는걸까요?

**Comment by stnqls** [comment]
welcomeSection을 pages/index로 옮겨서 해결.
